### ISSUE TITLE
Fullscreen vs Presentation API

### ISSUE THREAD

**Issue by annevk** [w3c/presentation-api#150] opened 2015-07-27 07:11 UTC
Could someone look at https://www.w3.org/Bugs/Public/show_bug.cgi?id=16502#c5 for me and see if there's anything we need to do?

I have the feeling we're heading towards a future where "fullscreen" and "presentation" are two different modes, but I might be missing something.

**Comment by duanyao** [comment] 2015-07-27 08:53
Just FYI, I also proposed 
["extend fullscreen API to support second screen"](https://lists.w3.org/Archives/Public/public-webscreens/2014Aug/0074.html) about one year ago, but got discarded. Yes, it seems "fullscreen" and "presentation" will become two seperate things.

**Comment by mfoltzgoogle** [comment] 2015-07-28 01:12
If I recall presenting part or all of the page's own content on a secondary screen was discussed but out of scope for what the Presentation API was intended.  There's a few differences we'd have to bridge:
- Presentation API applies to two or more separate documents, while Fullscreen API applies to an element within one document
- Fullscreen API is (nearly) almost always available, while Presentation API is only interesting when there secondary screens available.  An important feature of the Presentation API is enabling pages to detect this case and conditionally offer presentation.
- We specifically don't allow the API to target specific screens (along the lines of the proposal put forth).

That being said, a user requesting a fullscreen is a signal that the element in question is a good candidate for presentation on a secondary display, especially for `<video>`.  @duanyao I encourage you to review the proposal in Issue #13 and comment.

**Comment by annevk** [comment] 2015-07-28 07:27
If you find anything that needs collaboration, please don't hesitate to file a new issue at https://github.com/whatwg/fullscreen/issues/new. I'm going to close the bug filed against Fullscreen since it seems we're nowhere close to addressing the multiple monitor case.

**Comment by mounirlamouri** [comment] 2015-08-21 08:34
I do not think there is further action here. Closing.

**Closed by mounirlamouri** 2015-08-21 08:34 UTC
