### ISSUE TITLE
Presentation-api cast file working good on Chrome version 87, but it is not work on Chrome version 88

### ISSUE THREAD

**Issue by binhhuynhgit** [w3c/presentation-api#497] opened 2021-01-26 03:49 UTC
Hi Mark Foltz (Google),
I've issue with presentation-api. At present, I'm using present-api to cast to android tablet device. But It's working on Chrome version 87 so good, and now Chrome version 88 it's not working.

Describe step detail to reproduce:
1. Download and setup program "splashtop wired xdisplay" on Desktop and android tablet device.
2. Cast file.html (attach in this issue) to android tablet.

Pls help me check that issue.
My contact info: htbinh230989@gmail.com

**Comment by rdrrichards** [comment] 2021-01-26 14:37
I was coming here this morning to see if anyone was having the same issue. Looks like I am not the only one.

I submitted a bug to the Chromium team: https://bugs.chromium.org/p/chromium/issues/detail?id=1170057. The bug includes a repro.

All I see now on the presenting screen is nothing but a field of grey. If I press F11, I can get out of kiosk mode, but the browser screen is all black. F12 doesn't work. I cannot get any feedback from the browser.

My application users are now calling it the *grey screen of death*. Our company has stopped automatic updates of Chrome, and rolled back anyone who got the update before we caught this.

Any one have any clue what has gone wrong?

Thanks!!

**Comment by mfoltzgoogle** [comment] 2021-01-26 18:04
Hi @binhhuynhgit, you may have encountered the same bug as @rdrrichards - do you mind checking the bug they linked?

If it is a different bug then please file an issue at https://crbug.com/wizard and include links or attachments with the app that reproduces the issue as well as the device(s) and OS version(s).

Thanks!

**Comment by binhhuynhgit** [comment] 2021-01-27 01:10
Hi @mfoltzgoogle, @rdrrichards
I've quick check with Chrome version 88 and detect some deprecations and removals in Chrome 88 as below:
"Chrome 88 beta was released on December 3, 2020 and is expected to become the stable version in the third week of January 2021.
Don't allow popups during page unload (enterprises)
Since Chrome 80, pages have no longer been able to open a new page during unloading using window.open(). Since then enterprises have been able to use the AllowPopupsDuringPageUnload policy flag to allow popups during page unload. Starting in Chrome 88, this flag is no longer supported."

Refer link to: https://developers.google.com/web/updates/2020/12/chrome-88-deps-rems. I don't know those changes affect to Presentation API?

**Comment by binhhuynhgit** [comment] 2021-01-28 07:15
Hi @mfoltzgoogle, @rdrrichards 
I think I found my root cause, because Flash player is gone on Chrome version 88. So, I'm using iframe on content page and flash it's not working via presentation-api.

Any things else, @rdrrichards?

**Comment by rdrrichards** [comment] 2021-01-28 11:35
@binhhuynhgit 

Our applications do have that in common. I do use an iframe to host an application in the presenting window. Is there some sort of work around for that? The application we host in an iframe is a third party application we use to view images.

**Comment by rdrrichards** [comment] 2021-01-29 20:26
@binhhuynhgit, @mfoltzgoogle ,

Looks like the chromium team has a fix in the works. 

My repro application, and my production application *are working* with Chrome Canary version 90.0.4402.0.

**Comment by binhhuynhgit** [comment] 2021-02-01 04:23
Hi @rdrrichards,
I tried it and working OK. The seem it was fixed on Chrome Canary version 90.0.4402.0. But it's not official version. 
Thanks for your info, @rdrrichards.

**Comment by rdrrichards** [comment] 2021-02-01 13:06
@binhhuynhgit

At least, you can look forward to this issue being fixed in Chrome 90.

**Comment by eliasmikkola** [comment] 2021-02-02 11:59
Can also confirm the same behaviour while casting an URL from same domain. PresentationRequest opens window on selected external screen, but freezes after initialisation. The whole Chrome process sometimes crashes while doing so.

**Comment by binhhuynhgit** [comment] 2021-02-03 06:40
> @binhhuynhgit
> 
> At least, you can look forward to this issue being fixed in Chrome 90.

Yep @rdrrichards. I think wait to next release of Chrome 90. But don't know how long?

**Comment by rdrrichards** [comment] 2021-02-03 17:58
@binhhuynhgit Google this: chrome 90 release date

**Comment by mfoltzgoogle** [comment] 2021-02-22 21:57
Hi @binhhuynhgit, we were able to land a potential fix for this issue in Chrome 89, which will be released to all users on or around March 2. 

If your application requires Flash, then I'm afraid there's not much I can do, as Flash is no longer supported in Chrome.

**Comment by mfoltzgoogle** [comment] 2021-02-22 21:59
@eliasmikkola If your issue reproduces on Chrome 89, can you file a bug at https://crbug.com/wizard with steps to reproduce and assign it to mfoltz@chromium.org?

I'm closing this issue out in GitHub as these are Chrome implementation bugs and not spec issues.  Folks can follow up on these in the Chromium bug tracker.

**Closed by mfoltzgoogle** 2021-02-22 21:59 UTC
