### ISSUE TITLE
1-UA and 2-UA details

### ISSUE THREAD

**Issue by hsablonniere** [w3c/presentation-api#164] opened 2015-08-21 09:53 UTC
Hi everyone ;-)

In many places, we can find references to 1-UA and 2-UA ([Chromium Intent to Ship](https://groups.google.com/a/chromium.org/forum/#!topic/blink-dev/YKVnS429hns), Firefox bugzilla [#1184036](https://bugzilla.mozilla.org/show_bug.cgi?id=1184036) & [#1184073](https://bugzilla.mozilla.org/show_bug.cgi?id=1184073), spec Github issues...) but I cannot find a formal definition in the spec.

Here's what I understood :
* 1-UA is for non Web capable presentation displays, the UA initiating the request is rendering the page himself and streams it to another presentation display.
* 2-UA is for Web browser capable presentation displays such as the Chromecast, Matchstick...

The description in Bugzilla [#1184036](https://bugzilla.mozilla.org/show_bug.cgi?id=1184036) regarding 1-UA mentions the Chromecast. It confuses me. I thought it was a 2-UA presentation display.

In the Chromium Intent to Ship post, it says that 1-UA is not implemented yet but it will be before the end of the year. I'm confused when they say they will implement 1-UA even if browser vendors are free to do so. I can't find where the spec mentions that.

Thanks.

**Comment by anssiko** [comment] 2015-08-21 11:18
Thanks for the feedback. Perhaps Chromium participants in this group have some language in their design doc that could be reused to clarify this in the introduction section. I can confirm that this terminology has caused some confusion around people not following the work closely and we should clarify this. Not a blocker, so assigning P3.

**Comment by hsablonniere** [comment] 2015-08-21 12:14
Thx

**Comment by hsablonniere** [comment] 2015-08-21 12:19
Thanks @anssiko.

If found this in the charter :
> Content mirroring, whereby a web application requests display of the content shown in its own browsing context (i.e., page) on a secondary display, is out of scope.

But it's about mirroring which seems to be different from 1-UA.

**Comment by tidoust** [comment] 2015-08-21 13:01
The 1-UA and 2-UA possibilities are described in the spec introduction, except they are not given specific names there. Given that we keep referring to them as 1-UA and 2-UA in the group and elsewhere, it makes sense to mention these terms in the spec. One quick and easy fix would be to add something along the lines of "(commonly referred to as the 1-UA case)" next to the relevant bits.

For reference, the relevant bits are:

- **1-UA**: "For example, when a presentation display device is attached using HDMI or Miracast, the same UA that acts as the controller renders the presentation. Instead of displaying the presentation in another window on the same device, however, it can use whatever means the operating system provides for using the external presentation displays. In such a case, both the controller and presentation run on the same UA and the operating system is used to route the presentation display output to the presentation display."
- **2-UA**: "If the presentation display is able to render HTML documents and communicate with the controller, the controller does not need to render the presentation. In this case, the UA acts as a proxy that requests the presentation display to show and render the presentation itself."

See: http://w3c.github.io/presentation-api/#introduction

FWIW, the charter contains similar wording in the scope section as well:
http://www.w3.org/2014/secondscreen/charter.html#scope

**Comment by hsablonniere** [comment] 2015-08-21 13:07
Thanks very much @tidoust. I re-read both sections and it's crystal clear now ;-). It's just missing the references to 1-UA and 2-UA in the spec as you mentioned.

How does this work? Will someone handle this when P3 is up? I've never done this, maybe I can propose a PR...

**Comment by tidoust** [comment] 2015-08-21 13:23
You're most welcome to propose a pull request for this, @hsablonniere!

You'll find instructions on the group's wiki (nothing specific, really, just the fact that we run tidy on the spec before committing):
https://www.w3.org/wiki/Second_Screen/Work_Mode#Direct_Spec_Contributions

**Comment by avayvod** [comment] 2015-08-21 13:32
1UA means there's only one user agent instance that renders both the controlling and presentation pages. This UA instance in running on the controlling device and the presentation page is rendered offscreen on that device and the pixels are streamed somehow to the second screen. There're still two separate pages involved so it's not like mirroring (e.g. tab mirroring in Chrome) where there's only one page and it's just rendered on two screens. Streaming the offscreen presentation page to the second screen sometimes is referred to as mirroring since the technologies used for implemeting (e.g. Miracast or Cast Streaming) are the same. So mirroring the controlling page is out of scope for the API and mirroring the presentation page is just an implementation details like the 1UA or 2UA mode.

2UA means there're two instances of the user agent (same as in Chrome and Chrome or different, Chrome and Firefox, for instance) involved in presenting the page - one renders the controlling page and another one renders the presentation page.

Both modes have different advantages and disadvantages, but these are just an implementation detail and that's why it's not in the spec. I agree that we might introduce the terms to the spec since these became so commonly used by the WG.

A Cast device can support both modes: it can render a web page and it also supports Cast streaming protocol which allows UA to stream an offscreen rendered page to it.

You're more than welcome to try doing a pull request yourself following the instructions: https://www.w3.org/wiki/Second_Screen/Work_Mode

**Comment by hsablonniere** [comment] 2015-08-21 14:41
I runned `tidy` installed from [here](http://www.htacg.org/binaries/) on the lasted `gh-pages` (no modifications) but it does some transformations on the source. Is it normal?

**Comment by tidoust** [comment] 2015-08-21 15:18
Hmmm, tidy's behavior can change a bit from one version to the other. The result should hopefully remain correct.

It seems that the (recent) version that you mention does not process ampersands as it used to be and drops the escaping of non ambiguous ampersands in particular. It is true that an `&` followed by a space does not need to be escaped:
http://www.w3.org/TR/html5/syntax.html#syntax-ambiguous-ampersand

(Adding `preserve-entities: true` to the tidy config would preserve the initial `&amp`. I would personally prefer that, so I'll prepare a PR)

**Comment by hsablonniere** [comment] 2015-08-21 17:25
Great.

**Comment by anssiko** [comment] 2015-08-24 08:38
Closed via https://github.com/w3c/presentation-api/pull/166.

**Closed by anssiko** 2015-08-24 08:38 UTC
Labels: P3
