### ISSUE TITLE
Rethinking availability monitoring

### ISSUE THREAD

**Issue by anssiko** [w3c/presentation-api#81] opened 2015-04-27 14:10 UTC
The current events-based API for availability monitoring relies on the following side-effect: adding/removing a listener for the `availablechange` event starts/stops discovery. This is discouraged (see the historical discussion [1], also implementability concerns [2]).

A promise-based API is proposed as the solution [2][3].

[1] https://lists.w3.org/Archives/Public/public-device-apis/2011Sep/0025.html
[2] https://lists.w3.org/Archives/Public/public-secondscreen/2015Apr/0079.html
[3] https://lists.w3.org/Archives/Public/public-secondscreen/2015Apr/0068.html

**Comment by obeletski** [comment] 2015-04-27 15:28
Hi All,

First of all, I agree with Anssi, that availability monitoring could be improved and because of multiple reasons. One of the reasons is that current API design makes it very simple for web developers to start continuous monitoring and then to forget stopping it. Discovery is expensive process that could  prevent device from entering power saving/efficient mode. 

I also agree that it is good to optimize the most common one "Find out whether there are available display(s), and if yes, show content on the display chosen by the user." I would like to make an addition to that description -  "if external device is not found then stop monitoring and forget that we ever wanted to use the second screen". 

Then there is a less common case that we still need to support - "Find out whether there are available display(s), and if yes, show content on the display chosen by the user." + keep monitoring for new devices because there could be better presentation destination appearing in the future. We should keep discovery process running in that case. Additionally, we  need to provide for developers an explicit mechanism for stopping discovery then.

After listing  those cases side by side I realized that I have already seen that approach implemented in Geolocation API [1]. There are three methods: to acquire position once, to start continuous watching and stopping the watch. We can follow the same pattern here:

```
partial interface NavigatorPresentation {
  Promise checkForAvailability(/*DOMString presentationUrl, params*/);
  Long watchForAvailability(/*DOMString presentationUrl, params*/);
  clearAvailabilityWatch( long watchId);
}
```
Method checkForAvailability runs discovery one time and stops after that. Last two methods would provide exactly the same functionality that is available in current design with callback attribute onavailablechange and corresponding event. New approach makes developers aware that browser starts doing extra work when monitoring in active. All that clarity comes with the price of adding new methods to proposed API. The other thing is that proposal mixes promises and callbacks together. I am sure, there might be a better way to design it.

[1] http://dev.w3.org/geo/api/spec-source.html#geolocation_interface

**Comment by mwatson2** [comment] 2015-04-27 16:58
Another common use-case is "Find out whether there are available
displays(), and if yes, show an icon to the user. When there are no
available displays, remove / dim the icon". Clicking the icon is what would
trigger display selection and presentation of content. I think this
use-case may be more common than the one in which remote display of content
is automatic as soon as an available display appears.

**Comment by mfoltzgoogle** [comment] 2015-04-28 00:19
Recasting the two scenarios in https://github.com/w3c/presentation-api/issues/81#issuecomment-96709089:

1.  Page checks screen availability once on startup and offers user opportunity to present.  If no screen is found, perhaps the user can manually check later using UI on the page or in the UA.

2. Page checks availability automatically and events the page whenever there is a transition.  This way the page (or the UA) could dynamically offer the opportunity to present. There are concerns that use of this mode could lead to power consumption issues for the presenting device if the discovery implementation prevents it from entering a power saving mode.

The API proposed by @avayvod does address the two modes of use:

```
partial interface NavigatorPresentation {
  Promise<AvailabilityListener> listenForAvailability(/*DOMString
presentationUrl, params*/);
}

interface AvailabilityListener : EventTarget {
  readonly attribute boolean available;
  attribute EventHandler onavailablechange;
}
```

For mode 1, the caller would invoke 

    listenForAvailability.then(function(listener) {
      if (listener.available) offerPresentation();
    }

For mode 2, the caller would invoke

    listenForAvailability.then(function(listener) {
      if (listener.available) {
        maybeOfferPresentation(true)
      } else {
        listener.onavailablechanged = maybeOfferPresentation
      }
    }

Regarding concerns over power usage, the UA could likely optimize to only perform active discovery when the page with an  `AvailabilityListener` was active and available for user input (i.e., the foreground tab).  This would limit the usability in contexts like Service Workers but I think that's a reasonable tradeoff.  I would like to hear if there are any other implementation experiences for similar APIs.

**Comment by obeletski** [comment] 2015-04-28 07:25
```AvailabilityListener``` definitely can get the job done for both modes. One issue still has to be sorted out. I understood from @avayvod post [1] about  ```AvailabilityListener``` that discovery process is running even if ```onavailablechanged``` callback is not set and ```available``` attribute can still change in runtime depending on the availability of the external screens. That means that monitoring has to be explicitly stopped to make  mode 1 example complete.  Would it make scene to add ```cancel``` method to the  ```AvailabilityListener```? Any better ideas?
```
listenForAvailability.then(function(listener) {
  if (listener.available) {
  /* Stop the listener here */
  offerPresentation();
  }
}
```

[1] https://lists.w3.org/Archives/Public/public-secondscreen/2015Apr/0079.html

**Comment by anssiko** [comment] 2015-04-28 14:35
Good discussion. When we start to converge someone should craft a PR to be reviewed.

AFAIK Chrome suspends Device Orientation and other sensors in background pages. I also think some implementations might throttle and/or disable canvas, video, setTimeout, rAF in background pages too. And on mobile suspend these features altogether to save battery and CPU.

**Comment by anssiko** [comment] 2015-05-11 09:08
We seem to be in agreement that [1] with some tweaks [2] is a better solution than what we currently have in the spec.

@avayvod Could you update your proposal baking in feedback by F2F?

@obeletski Is this a functional gap or a quality of implementation issue (performance, power/resource consumption etc.)? If QoI we should get some more implementation feedback to see whether an explicit cancel is required. 

@mwatson2 IIUC your proposal is similar to the reader view in e.g. Safari: an icon in chrome is lit when the web content is identified as an article. Also used for discovering RSS feeds back in the days when RSS was a thing. If so, you should redirect your comment to [3].

[1] https://lists.w3.org/Archives/Public/public-secondscreen/2015Apr/0079.html
[2] https://lists.w3.org/Archives/Public/public-secondscreen/2015May/0005.html
[3] https://github.com/w3c/presentation-api/issues/26

**Comment by mfoltzgoogle** [comment] 2015-05-11 20:31
Rather than add a `cancel` method we could write the `AvailabilityListener` API as follows:

```
partial interface NavigatorPresentation {
  AvailabilityListener listenForAvailability(/*DOMString presentationUrl,
      params*/);
}

interface AvailabilityListener : EventTarget {
  Promise<boolean> getAvailability();
  attribute EventHandler onavailablechange;
}
```

The UA would not run discovery if:

* there were no handlers on `onavailablechange`
* there was no unresolved `Promise` from `getAvailability`

Even if there were listeners, the UA could also suspend discovery if there was no opportunity to start presentation (i.e., screen was off, tab was in the background, etc.) as a power optimization.

I would like to understand the role of the `presentationUrl` and `params` in the API; @avayvod, they were part of your original proposal.

**Comment by avayvod** [comment] 2015-05-11 22:20
We could just monitor availability as long as the received
AvailabilityListener instance is alive. The downside is that if the page
discards the instance but attached a listener to it beforehand, the
instance will live as long as the page. I'm not sure about the use case
though when a presentation capable page would want to stop discovery unless
it was navigated from. Are there any existing examples why this is needed
on a more granular level than "page is closed/navigated"?

The URL and optional parameters could be used for device filtering in the
future.

Rather than add a cancel method we could write the AvailabilityListener API
as follows:

partial interface NavigatorPresentation {
  AvailabilityListener listenForAvailability(/*DOMString presentationUrl,
      params*/);
}

interface AvailabilityListener : EventTarget {
  Promise<boolean> getAvailability();
  attribute EventHandler onavailablechange;
}

The UA would not run discovery if:

   - there were no handlers on onavailablechange
   - there was no unresolved Promise from getAvailability

Even if there were listeners, the UA could also suspend discovery if there
was no opportunity to start presentation (i.e., screen was off, tab was in
the background, etc.) as a power optimization.

I would like to understand the role of the presentationUrl and params in
the API; @avayvod <https://github.com/avayvod>, they were part of your
original proposal.

—
Reply to this email directly or view it on GitHub
<https://github.com/w3c/presentation-api/issues/81#issuecomment-101039366>.

**Comment by obeletski** [comment] 2015-05-12 07:55
Not being able to stop discovery looks like a functional gap to me in addition to performance issues.

Here is what I was able to find:

According to  "UPnP Device Architecture 2.0" document [1] discovery process works like that:
- When a control point is added to the network, the UPnP discovery protocol allows that control point to search for devices of interest on the network. 
- When a device is added to the network, the UPnP discovery protocol allows that device to advertise its services to control points on the network (multicast).

In the first case waiting time for advertisement response after search request can be limited, so cancelling is less important. In the second case control point continuously listens for the notifications until it is stopped. We need cancel method here if we want to stop discovery.

Other example is Samsung Media Control SDK [2]. In Samsung Media Control SDK 1.0.4 discovery is handled by `SmcDeviceFinder` class that has `start` and `stop` methods to control discovery process.

Same functionality exists in Android's `MediaRouteProvider`, where discovery can be switched on/off with the help of `setDiscoveryRequest` method [3].

I think that the latest interface update proposed by @mfoltzgoogle  https://github.com/w3c/presentation-api/issues/81#issuecomment-101039366 will get the job done for discovery stopping as well.

[1] http://upnp.org/specs/arch/UPnP-arch-DeviceArchitecture-v2.0.pdf
[2] http://developer.samsung.com/galaxy#media-control
[3] http://developer.android.com/reference/android/support/v7/media/MediaRouteProvider.html

**Comment by avayvod** [comment] 2015-05-13 13:47
MediaRouteProvider is not for the app that needs to get screen availability. There's MediaRouter.removeCallback() that means the app doesn't want to get updates about the routes anymore. It is advised to remove callback in onStop/onPause. The UA could definitely stop discovery for the pages that are not visible and resume it when the page becomes visible.

I don't think the page should explicitly manage the power / CPU / bandwidth consumption by the UA's discovery process. I also don't think the UA should rely on the page to do the right thing in order to stop discovery.

I also think that having to wait for two promises to be resolved to simply get availability status as in https://github.com/w3c/presentation-api/issues/81#issuecomment-101039366 is an overkill and is as non-standard as having an event fire immediately as soon as the event handler is attached (what we are trying to solve).

**Comment by matt-hammond-bbc** [comment] 2015-05-13 14:49
I can see the logic in having an approach that meets the two use cases described ("one-shot" and "continuous", for want of better ways of describing them) - particularly if it enables the UA reduces power consumption.

In this idea mentioned earlier in this thread:

    interface AvailabilityListener : EventTarget {
    Promise<boolean> getAvailability();
        attribute EventHandler onavailablechange;
    }

I'm wondering about the semantics of getAvailability()...

The proposal shows a <boolean> to be passed by the Promise during resolution. Presumably this is intended as a flag that is true for availability and false for unavailability? Is this what is intended?

My understanding is that a Promise "resolves" if the system transitions to the desired/new state after the promise is made; but also resolves immediately if it is already in that state. Therefore if this is the intended behaviour then I don't see how it works.

I think the only sensible behaviour is for the promise to resolve only if there is availability (not unavailability).

---

I'm also interested by the suggestion that the URL and additional params get passed to the availability checking process.

If we go down this route, it then feels redundant to be re-specifying the URL (and params?) when subsequently calling startSession(). What if a resolved promise notifying of availability returned an object that provided the startSession() and/or joinSession() methods and carried that state (the URL and any params) with it?

----

Finally, I can see uses for the "params" if provided to the process of starting a session. I've been thinking about the relationship between HbbTV and this API. It would be useful if the URL can be supplemented with additional data that will be used if the URL is being launched on an HbbTV device, or ignored if it is not.

Perhaps this would also provide a route to a clean mapping for DIAL too?

**Comment by mfoltzgoogle** [comment] 2015-05-13 18:22
> The proposal shows a to be passed by the Promise during resolution. Presumably this is intended as a flag that is true for availability and false for unavailability? Is this what is intended?

Yes, that's what's intended.

> My understanding is that a Promise "resolves" if the system transitions to the desired/new state after the promise is made; but also resolves immediately if it is already in that state. Therefore if this is the intended behaviour then I don't see how it works.

The Promise resolves when the browser has an answer to the query (not necessarily when the underlying system changes state).  Since answering the question of "are screens available" likely involves cross-process or cross-device communication, using a Promise frees up Javascript execution while the browser figures that out.

 > I think the only sensible behaviour is for the promise to resolve only if there is availability (not unavailability).

Suppose there are no screens available; this means that the browser would have to monitor continuously while that Promise is pending.   This ends up being the same as adding an event handler to `onavailablechange` to monitor all availability changes.

> If we go down this route, it then feels redundant to be re-specifying the URL (and params?) when subsequently calling startSession(). What if a resolved promise notifying of availability returned an object that provided the startSession() and/or joinSession() methods and carried that state (the URL and any params) with it?

If we go with this approach I could see moving `startSession()` to the `AvailabilityListener` interface so the URL gets specified once for screen availability and presentation request.   `joinSession()` does not have a prerequisite of waiting for screen availability so the need is less clear.

> Finally, I can see uses for the "params" if provided to the process of starting a session. I've been thinking about the relationship between HbbTV and this API. It would be useful if the URL can be supplemented with additional data that will be used if the URL is being launched on an HbbTV device, or ignored if it is not.

I think the params are intended to communicate to the user agent additional requirements for the remote screen (yet to be determined).   For passing information to the remote presentation there are plenty of ways  to use URLs: query parameters, URL fragments, or messaging after the presentation is connected.

Perhaps @avayvod can clarify the use of parameters (and show some examples)?

**Comment by matt-hammond-bbc** [comment] 2015-05-13 18:44
> The Promise resolves when the browser has an answer to the query (not necessarily when the underlying system changes state). Since answering the question of "are screens available" likely involves cross-process or cross-device communication, using a Promise frees up Javascript execution while the browser figures that out.
>
>> I think the only sensible behaviour is for the promise to resolve only if there is availability (not unavailability).
>
> Suppose there are no screens available; this means that the browser would have to monitor continuously while that Promise is pending. This ends up being the same as adding an event handler to onavailablechange to monitor all availability changes.

Thanks for the explanation. I understand the intended behaviour now.

I would suggest that the method returning the promise be named something such as `checkAvailability` or `determineAvailability`. For me, `getAvailability` implies a passive retrieval of some kind of state information and led me to my previous conclusions.

> I think the params are intended to communicate to the user agent additional requirements for the remote screen (yet to be determined). For passing information to the remote presentation there are plenty of ways to use URLs: query parameters, URL fragments, or messaging after the presentation is connected.

Yes, this is what I had in mind. Parameters needed in the process of establishing availability and/or starting/joining the session.

> Perhaps @avayvod can clarify the use of parameters (and show some examples)?

I can offer some strawman examples for that would be useful for an implementation that can launch applications on an HbbTV 2.0 television/set-top-box:

* `hbbtv.appId` (integer) and `hbbtv.orgId` (integer) ... necessary to allow the presentation to combine itself with broadcast content
* `hbbtv.appEndpoint` (string) ... needed to establish the communication channel.

**Comment by mwatson2** [comment] 2015-05-14 00:46
On Mon, May 11, 2015 at 2:08 AM, Anssi Kostiainen <notifications@github.com>
wrote:

> We seem to be in agreement that [1] with some tweaks [2] is a better
> solution than what we currently have in the spec.
>
> @avayvod <https://github.com/avayvod> Could you update your proposal
> baking in feedback by F2F?
>
> @obeletski <https://github.com/obeletski> Is this a functional gap or a
> quality of implementation issue (performance, power/resource consumption
> etc.)? If QoI we should get some more implementation feedback to see
> whether an explicit cancel is required.
>
> @mwatson2 <https://github.com/mwatson2> IIUC your proposal is similar to
> the reader view in e.g. Safari: an icon in chrome is lit when the web
> content is identified as an article. Also used for discovering RSS feeds
> back in the days when RSS was a thing. If so, you should redirect your
> comment to [3].
>
​No, I was just pointing out what I understand to be the most common use
case under the "flinging" category: you are viewing content in a web page
and there is an icon which lights up when there is a device available to
which the content can be "flung". The icon light up / dims as the remote
device(s) comes and goes. cf Cast, AirPlay etc.​

[1]

**Comment by avayvod** [comment] 2015-05-19 12:57
I've created a prototype change and have a pull request ready to be discussed:
- https://github.com/w3c/presentation-api/compare/gh-pages...avayvod:availability-monitoring
- http://avayvod.github.io/availability.html

**Comment by tidoust** [comment] 2015-05-20 09:05
PROPOSED RESOLUTION: For issue #81, adopt proposal to have a "getAvailability" method on NavigatorPresentation that returns a Promise to get an AvailabilityListener (or observer) with a boolean "available" property and an "availablechange" event. Promise is rejected when user agent does not support background monitoring. startSession triggers discovery. No requirement on frequency of discovery (there may not be any in some period of time)

**Comment by tidoust** [comment] 2015-05-20 09:05
ACTION: Anton to update startSession example to use implicit discovery (pending pull request) [recorded in http://www.w3.org/2015/05/20-webscreens-minutes.html#action01]

**Comment by tidoust** [comment] 2015-05-20 09:05
ACTION: Oleg to clarify implicit/explicit mechanisms in the spec, and review the relevant algorithms and examples. [recorded in http://www.w3.org/2015/05/20-webscreens-minutes.html#action02]

**Comment by tidoust** [comment] 2015-05-20 09:06
See relevant discussion at F2F in Berlin:
http://www.w3.org/2015/05/20-webscreens-minutes.html#item01

**Comment by obeletski** [comment] 2015-05-28 12:09
During F2F meeting we agreed to have an `AvailabilityListener` for explicit monitoring of screen availability. We also agreed that cancel method is not required and UA start/stop discovery when needed. 
Actually there were two proposals and we did not look in the details at second modification of the original interface. Let’s take a second look and compare both. The main difference is that in the first proposal access to the `AvailabilityListener` is behind the promise and in the second proposal access to one method of the interface returns the promise for the user - `getAvailability()`. In both cases there is only one promise that user code has to wait to resolve.

**First proposal:**
```
partial interface NavigatorPresentation {
  Promise<AvailabilityListener> listenForAvailability(…);
}

interface AvailabilityListener : EventTarget {
  readonly attribute boolean available;
  attribute EventHandler onavailablechange;
}
```
Access to the interface is behind the promise. Discovery starts when interface is instantiated even if there is no event listener attached.

**Pros**
* Continuous discovery with always up to date value of available property.

**Cons**
* Difficult to stop discovery. If we want to stop it, then we have to remove all event listeners and then drop all the references to the instance of the `AvailabilityListener` interface. After that discovery can be stopped at the next pass of garbage collector (UA can optimize that though).
* If presentation screen discovered while promise to get listener is being resolved, the available will be set to true right after construction and `availablechange` event will never be fired. For API users that means that they will have to use both available property in addition to event listeners.

**Second proposal:**

```
partial interface NavigatorPresentation {
  AvailabilityListener listenForAvailability(…);
}

interface AvailabilityListener : EventTarget {
  Promise<boolean> getAvailability();
  attribute EventHandler onavailablechange;
}
```
Access to the interface is not behind the promise, but access to the `getAvailability()` is. Discovery runs when there is least one event handler on `onavailablechange` or request to `getAvailability()` is made and promise still unsolved.

**Pros**
* Continuous discovery happens only when event listener is attached.
* Single run discovery started when `getAvailability()` is called and stopped immediately after promise resolved.
* API user can use only one out of two API methods for different usage models; there is no need to use both (property and even listener) for continuous case. For continuous monitoring event will be always delivered at least once.
* Clear indication to the UA when discovery should be stopped (no event listeners attached), so better optimization can be applied.

**Cons**
* Boolean property value available is under promise, so access to it will take time (unless there is an event listener attached, then it resolved without waiting).

**Comment by avayvod** [comment] 2015-05-28 13:13
Hi, IIRC we actually started looking at the second proposal and dismissed it in favor of the first one (the second one doesn't solve the problem with the event firing without actual state change, etc). For power saving platforms/implementations (e.g. mobile phones), we agreed that listenForAvailability() would reject the Promise and let the page know this way that it the discovery will run on demand when startSession() is called (so the page would show the Present button in 'try-me' state). This would match the Android behavior towards WiFi Direct discovery and discovery on Samsung devices as I understood.

The example code would be then (based on in progress change at [my GitHub repo](https://avayvod.github.io/availability.html):

```javascript

<!-- controller.html -->
<button id="castBtn" style="display: none;">Cast</button>
<script>
  // it is also possible to use relative presentation URL e.g. "presentation.html"
  var presUrl = "http://example.com/presentation.html";
  // the cast button is visible if at least one presentation display is available
  var castBtn = document.getElementById("castBtn");
  // the availability listener object.
  var availability = null;
  // show or hide cast button depending on display availability
  var handleAvailabilityChange = function() {
    castBtn.style.display = availability.current ? "inline" : "none";
  };
  // availablechange event is fired when the presentation display availability changes
  navigator.presentation.getAvailability(presUrl).then(function(availabilityObj) {
    // availability.current will be updated by the UA as long as the availability
    // object is alive. It is advised for the web developers to discard of the object
    // as soon as it's not needed (e.g. when startSession() succeeded).
    availability = availabilityObj;
    handleAvailabilityChange();
    availability.onchange = function() { handleAvailabilityChange(); };
  }, function(error) {
    // background discovery is not supported, let startSession() be called to do one-time discovery.
    castBtn.style.display = "inline";
  });
</script>
```

**Comment by avayvod** [comment] 2015-05-28 13:25
See the meeting minutes about the issue: http://www.w3.org/2015/05/20-webscreens-minutes.html#item01

**Comment by obeletski** [comment] 2015-05-28 15:58
@avayvod, could you elaborate a bit. What is the problem of event firing without actual state change?

**Comment by avayvod** [comment] 2015-05-28 16:50
@obeletski please, read the original description of this issue, it has a brief summary and some links to mailing list discussions. From the meeting notes:

```
Mark_Watson: So, startSession handles this, but some way to monitor available screens in the background would be pretty useful. Problem is enabling continuous monitoring when an event handler is attached to a property is considered bad practice, right?

Mark_Foltz: right.

Anssi: Adding an event listener should not have side effect, that's a shared practice.

Mark_Foltz: So, how does geolocation handle this?

Anssi: Example of the deviceOrientation. If your phone is staying flat and you attach an event listener, you will not get an event up until the phone moves. The spec cannot force the user agent to fire an event when the event listener is attached.
```

Now imagine the following scenario: the UA started running background availability monitoring of second screens because page A attached a listener to |onavailablechange|. The UA finds the screens and fires an event - page A knows there're screens available. Then page B is loaded by the user and it attaches its own listener - if the UA follows good practices of implementing events, it will not fire the event to page B because the availability state hasn't changed. But page B doesn't know the current state so it will assume there's no devices available.

The common practice is to provide a current state property - which is what the first proposal is about.
If we follow the second proposal - the page would have to wait until the promise resolves and attach a listener only then. Otherwise it would get both the promise resolved and event firing depending on when it attached the listener.

As long as the page attached a listener, it doesn't matter if there's a property we have to update in runtime. There's a way to stop background discovery if the page cares (detach the event listener and abandon the reference to the AvailabilityListener) but I would expect most of the pages won't and would rely on the browser to optimize the battery and performance for them.

**Comment by obeletski** [comment] 2015-05-29 13:16
Thanks for detailed explanation. I perfectly understand idea behind not firing of the events when nothing is really happening. My assumption was that since we create new interface then it is equivalent to starting of the new discovery process. Naturally, page will get notifications about all discovered devices after that. In that case  even though device already signaled with the event to page A, the same device availability will be reported in page B over new AvailabilityListener instance. Otherwise, if with AvailabilityListener interface we provide access to the discovery process running in the background, then yes, page B will get no notifications about device that has been reported to page A.

**Comment by anssiko** [comment] 2015-06-01 11:48
@obeletski With @avayvod's explanation and clarifications, do you agree with the proposed resolution we landed on at F2F?

**Comment by mfoltzgoogle** [comment] 2015-06-01 23:39
Per @obeletski's last comment, in Chrome the discovery process is shared among all clients of the Presentation API.  Chrome can "force" events to be fired as handlers are added but it would require extra bookkeeping and doesn't seem right: multiple pages are observing the same state but some would get events and some won't. 

So I would also land in favor of Proposal 1, as it would simplify our implementation, and yours if I understand correctly (Samsung's implementation would just reject the Promise).

We might include a non-normative note that a live `AvailabilityListener` would likely require the UA to do background discovery, it may not always be available, and Web authors should be aware of power implications when it is.

**Comment by obeletski** [comment] 2015-06-02 14:52
Thanks everyone for taking a second look at the issue. @anssiko, with explanations provided by @avayvod and @mfoltzgoogle I agreed resolution proposed at F2F.

**Comment by avayvod** [comment] 2015-06-03 15:59
Hey, I've updated my PR for the issue: https://github.com/w3c/presentation-api/pull/89
See the updated spec at http://avayvod.github.io/availability.html

**Comment by obeletski** [comment] 2015-06-04 08:07
Quick comment:
"The user agent might not support continuous availability monitoring due to platform or power consumption restrictions, for example. In this case the Promise returned by getAvailability() is rejected and the algorithm for monitoring the list of available presentation displays will only run as part of the session start or join algorithms."

UA does not have to run monitoring algorithm for joining session, only when starting it.

**Comment by avayvod** [comment] 2015-06-05 11:43
Updated the PR and the demo files with Oleg and Mounir's comments.

**Comment by mfoltzgoogle** [comment] 2015-06-09 18:16
I believe PR #89 by @avayvod addressed the topics and comments in this particular issue.  If there are further changes requested let's track under a different issue.

**Closed by mfoltzgoogle** 2015-06-09 18:16 UTC
Labels: action, F2F, resolution
